### ISSUE TITLE
Understand the meaning of each cause of death

### ISSUE THREAD

**Issue by YizhouChens1933173** [PatUoe/DS4D-Group-Work#11]
Try to be familiar with the meaning of the cause of death and find some relevant icons to explain the cause of death.

**Comment by PatUoe** [comment]
I and Chen will work on the icons.

**Comment by PatUoe** [comment]
I and YiZhou will work on that tomorrow.

**Comment by YizhouChens1933173** [comment]
> I and YiZhou will work on that tomorrow.

Especially the largest causes of death in each category.

**Comment by mjy9611** [comment]
Yes , and I can translate the death cause for you guys now so that we can do it more effectively
