### ISSUE TITLE
About the improvement of the website visualization  and content

### ISSUE THREAD

**Issue by mjy9611** [PatUoe/DS4D-Group-Work#12]
I suppose that black and white style would be much better for people to think of death, since it is a serious and thought-provoking topic. Also, the visualization can be improved to be more like telling a story like adding some interesting connections to link the parts of the visualization. What do you think of it??

**Comment by PatUoe** [comment]
I have uploaded a new version of website according to our data comics. If there any problem. Leave me a message or call me.

**Comment by YizhouChens1933173** [comment]
I agree with you. The part of introducing the cause of death can be represented by some icons so that the audiences can better understand them. The part of the map is a bit difficult because of the limited colour. I will try to deal with it well.

**Comment by mjy9611** [comment]
The website now is good. Good Job!
