### ISSUE TITLE
Make the slides

### ISSUE THREAD

**Issue by YizhouChens1933173** [PatUoe/DS4D-Group-Work#15]
We can sort out our ideas again according to the checklist and then make the slides.

**Comment by PatUoe** [comment]
I have done the part of finding. Sorry for response so late. Luckily we have done the presentation.

**Comment by mjy9611** [comment]
Sorry for waiting, I improved some gramma and the visualization problem in the slides. Please check it!

**Comment by mjy9611** [comment]
I have improved some gramma in the slide to make it perfect. Please check it
