### ISSUE TITLE
Feedbacks of the presentation

### ISSUE THREAD

**Issue by PatUoe** [PatUoe/DS4D-Group-Work#16]
1. need legend of the age period
2.explainations why a skeleton equals 96 death

More feedback needed

**Comment by YizhouChens1933173** [comment]
OK. I will modify it as soon as possible.

**Comment by Jishenshen** [comment]
Could you please provide the raw data?

**Comment by PatUoe** [comment]
More feedback from tutors: the graphs don't seem to support what you are saying - I read that the death rate was decreasing in Scotland? Good context though! Very nice animations and aesthetics. Powerful presentation, and some interesting strategies coming through. Surprised that 75% of people in your age group die from poisoning

**Comment by YizhouChens1933173** [comment]
I added some explanations about the design process in the final report. More detail of our project should be included in the final report.

**Comment by PatUoe** [comment]
I have written something about the data analysis.

**Comment by PatUoe** [comment]
Finished all the document for submission

**Comment by PatUoe** [comment]
We have modified something

**Comment by YizhouChens1933173** [comment]
We should also add the references that we read before when we write the report.

**Comment by PatUoe** [comment]
I have read one called More Than Telling a Story: Transforming Data into Visually Shared Stories.
Here is the link:https://ieeexplore.ieee.org/document/7274435

**Comment by YizhouChens1933173** [comment]
OK. I will add this into our report.
